package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Hello.idl
* Saturday, 4 November, 2023 8:35:56 PM IST
*/

public interface HelloOperations 
{
  String pingHello ();
  void shutdown ();
} // interface HelloOperations
